{
  "hash": "bb30425a013ba7f1233d9f2cb371a7e7",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Biodiversity Intactness Index Change in the Phoenix Subdivision\"\ndate: 2025-12-06\ncategories: [MEDS, Python]\nimage: landsat_eight_image_of_phoenix.png\nformat:\n  html:\n    code-fold: false\n    embed-resources: true\npython: /opt/anaconda3/bin/python\njupyter: eds220-env\ncitation:\n  url: https://jwonyk.github.io/posts/biodiversity-intactness-index-change/\nbibliography: references.bib\n---\n\n**GitHub repository:** https://github.com/jwonyk/biodiversity-intactness-index-change\n\n## About\n\n#### Purpose\n\nThis repository contains the analysis for a project examining changes in the Biodiversity Intactness Index (BII) in the Phoenix subdivision of Maricopa County, AZ, from 2017 to 2020. Using 100 m BII data, the project explores how rapid urban growth may be affecting local biodiversity.\n\n#### Highlights\n\n-   Extracting and clipping BII rasters for 2017 and 2020 to the Phoenix subdivision boundary.\n-   Calculating the percentage of the subdivision area with BII ≥ 0.75 for both years.\n-   Mapping areas that lost high BII values (≥ 0.75) between 2017 and 2020.\n-   Situating the Phoenix subdivision within its broader geographic and urban context using additional vector/raster data and basemaps.\n\n#### About the data\n\n-   **Biodiversity Intactness Index (BII)**: BII data are taken from the `io-biodiversity` collection on the Microsoft Planetary Computer, which provides global 100 m BII projections for 2017–2020. For this project, the 2017 and 2020 rasters covering the Phoenix subdivision (bounding box: `[-112.826843, 32.974108, -111.184387, 33.863574]`) are loaded and then clipped to the Phoenix subdivision boundary to calculate metrics such as the percentage of area with BII ≥ 0.75.\n\n-   **Phoenix subdivision boundary**: The Phoenix subdivision boundary comes from the Census County Subdivision TIGER/Line shapefiles for Arizona. This polygon defines the analysis area, is used to clip the BII rasters, and provides geographic context for mapping within Maricopa County and the surrounding region.\n\n#### References\n\n-   Microsoft Planetary Computer, *Biodiversity Intactness Index (BII) Time Series, io-biodiversity Collection*, 2017–2020 \\[data file\\]. Available from the Microsoft Planetary Computer STAC catalog. \\[Accessed: Dec. 1, 2025\\]\n\n-   U.S. Census Bureau, *County Subdivision Shapefiles, Arizona (TIGER/Line)* \\[data file\\]. Available from the U.S. Census Bureau TIGER/Line shapefile download portal. \\[Accessed: Dec. 1, 2025\\]\n\n## Setup\n\nLoad required Python packages and configure the workspace.\n\n::: {#8259d732 .cell execution_count=1}\n``` {.python .cell-code}\n# Load in all necessary packages\nimport geopandas as gpd\nimport xarray as xr\nimport rioxarray as rioxr\n\nimport matplotlib.pyplot as plt\nimport matplotlib.patches as mpatches\nfrom matplotlib.colors import ListedColormap\n\nimport numpy as np\nimport contextily as ctx\nfrom shapely.geometry import box\n\nfrom pystac_client import Client  # To access STAC catalogs\nimport planetary_computer as pc  # To sign items from the MPC STAC catalog \n```\n:::\n\n\n## Read in Data\n\nImport the Census TIGER/Line shapefile and filter to the Phoenix subdivision.\n\n::: {#0fc3861e .cell execution_count=2}\n``` {.python .cell-code}\n# Load all county subdivisions for AZ\nsubdivisions = gpd.read_file('data/tl_2020_04_cousub/tl_2020_04_cousub.shp')  \n\n# Filter to Phoenix subdivision\nphoenix_subdivisions = subdivisions[subdivisions['NAME'] == 'Phoenix'].to_crs(epsg = 3857)\n```\n:::\n\n\n## Access\n\nQuery the Microsoft Planetary Computer STAC API for 2017 and 2020 BII rasters. We use the Client function from the `pystac_client` package to access the catalog:\n\n::: {#db9cba4c .cell execution_count=3}\n``` {.python .cell-code}\n# Set bounding box\nbbox = [-112.826843, 32.974108, -111.184387, 33.863574]\n\n# Access STAC catalog\ncatalog = Client.open(\"https://planetarycomputer.microsoft.com/api/stac/v1\")\n\n# Search BII raster for 2017 & 2020\nsearch_2017 = catalog.search(\n    collections = ['io-biodiversity'],\n    bbox = bbox,\n    datetime = '2017-01-01/2017-12-31')\n\nsearch_2020 = catalog.search(\n    collections = ['io-biodiversity'],\n    bbox = bbox,\n    datetime = '2020-01-01/2020-12-31')\n\n# Extract matching item from each search\nitem_2017 = list(search_2017.items())[0]\nitem_2020 = list(search_2020.items())[0]\n\n# Find the asset key\nitem_2017.assets.keys(), item_2020.assets.keys()\n```\n\n::: {.cell-output .cell-output-display execution_count=3}\n```\n(dict_keys(['data', 'tilejson', 'rendered_preview']),\n dict_keys(['data', 'tilejson', 'rendered_preview']))\n```\n:::\n:::\n\n\n## Read in BII Rasters\n\nOpen the raster assets into `xarray` objects.\n\n::: {#a1002fca .cell execution_count=4}\n``` {.python .cell-code}\n# Access the GeoTIFF from STAC\nasset_2017 = pc.sign(item_2017.assets['data'])\nasset_2020 = pc.sign(item_2020.assets['data'])\n\n# Read in raster to xarray DataArrays to clip and mask\nbii_2017 = rioxr.open_rasterio(asset_2017.href).squeeze()\nbii_2020 = rioxr.open_rasterio(asset_2020.href).squeeze()\n```\n:::\n\n\n## Clip Rasters to Phoenix Subdivision\n\nMatch CRS between raster and vector data, then clip the rasters to the subdivision boundary.\n\n::: {#5b564342 .cell execution_count=5}\n``` {.python .cell-code}\n# Match CRS before clipping\nphoenix_subdivisions_projection = phoenix_subdivisions.to_crs(bii_2017.rio.crs)\n\n# Clip the Phoenix subdivision to reduce size and keep only pixels inside\nbii_2017_clip = (bii_2017.rio.clip_box(*phoenix_subdivisions_projection.total_bounds)\n                         .rio.clip(phoenix_subdivisions_projection.geometry, phoenix_subdivisions_projection.crs))\nbii_2020_clip = (bii_2020.rio.clip_box(*phoenix_subdivisions_projection.total_bounds)\n                         .rio.clip(phoenix_subdivisions_projection.geometry, phoenix_subdivisions_projection.crs))\n```\n:::\n\n\n## Mapping Phoenix Subdivision\n\nPlot the Phoenix subdivision boundary over a basemap\n\n::: {#bb28db65 .cell execution_count=6}\n``` {.python .cell-code}\n# Reproject to Web Mercator for contextily\nphoenix_subdivisions_web = phoenix_subdivisions_projection.to_crs(epsg = 3857)\n\n# Compute true spatial aspect ratio from data bounds\nminx, miny, maxx, maxy = phoenix_subdivisions_web.total_bounds\nwidth = maxx - minx\nheight = maxy - miny\naspect_ratio = width / height  # width / height\n\n# Fix figure height and scale width accordingly\nfig_height = 7\nfig_width = fig_height * aspect_ratio\n\n# Create figure with true array ratio\nfig, ax = plt.subplots(1, 1, figsize = (fig_width, fig_height))\n\n# Plot the subdivision boundary\nphoenix_subdivisions_web.plot(ax = ax,\n                              edgecolor = 'blue',\n                              color = '#93E9BE',\n                              linewidth = 5, \n                              alpha = 0.5)\n\n# Add basemap\nctx.add_basemap(ax, source = ctx.providers.OpenStreetMap.Mapnik)\n\n# Add title and clean ticks\nax.set_title('Phoenix Subdivision overlay Arizona OpenStreetMap', \n             fontsize = 20, fontweight = 'bold')\nax.set_xticks([])\nax.set_yticks([])\n\n# Add legend\nborder_patch = mpatches.Patch(color = '#93E9BE', alpha = 0.5, \n                              label = 'Phoenix Subdivision')\n\nlegend_properties = {'weight': 'bold', 'size': 'large'}\n\nplt.legend(handles = [border_patch], loc = (0.1, 0.8),\n           prop = legend_properties, \n           handlelength = 2.5, handleheight = 2.5, handletextpad = 1.0,\n           borderpad = 1.0, labelspacing = 1.0)\n\n# Improve layout so elements do not overlap\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](index_files/figure-html/cell-7-output-1.png){width=890 height=663}\n:::\n:::\n\n\n## Calculate Percentage of Area With BII\n\nCompute the proportion of valid pixels in 2017 and 2020 exceeding the threshold (0.75)\n\n::: {#ff7e0014 .cell execution_count=7}\n``` {.python .cell-code}\n# Threshold representing high biodiversity intactness\nthreshold = 0.75\n\n# Boolean masks identify pixels meeting the threshold\nhigh_2017 = bii_2017_clip >= threshold\nhigh_2020 = bii_2020_clip >= threshold\n\n# Identify pixels inside the polygon with valid raster data\nvalid_2017 = ~bii_2017_clip.isnull()\nvalid_2020 = ~bii_2020_clip.isnull()\n\n# Count qualifying pixels and total valid pixels\nn_high_2017 = (high_2017 & valid_2017).sum().item()\nn_total_2017 = valid_2017.sum().item()\n\nn_high_2020 = (high_2020 & valid_2020).sum().item()\nn_total_2020 = valid_2020.sum().item()\n\n# Compute percentages\npct_2017 = (n_high_2017 / n_total_2017) * 100\npct_2020 = (n_high_2020 / n_total_2020) * 100\n\nprint(f\"Percentage of of area of the Phoenix subdivision with a BII of at least 0.75 in 2017: {pct_2017:.2f}\")\nprint(f\"Percentage of of area of the Phoenix subdivision with a BII of at least 0.75 in 2020: {pct_2020:.2f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nPercentage of of area of the Phoenix subdivision with a BII of at least 0.75 in 2017: 7.13\nPercentage of of area of the Phoenix subdivision with a BII of at least 0.75 in 2020: 6.49\n```\n:::\n:::\n\n\n## Result Summary\n\nUsing a threshold (BII ≥ 0.75) to test the high biodiversity intactness, the result in shown in the followings: 7.13% of the Phoenix subdivision met this criteria, but it dropped in 2020 to only 6.49%. The degradation over the three-year period shows the portion of subdivision with ongoing pressure on habitats.\n\n## Identify Areas That Lost High BII\n\nCreate a Boolean mask showing pixels that were BII ≥0.75 in 2017 but not in 2020.\n\n::: {#148c989d .cell execution_count=8}\n``` {.python .cell-code}\n# Identify pixels that no longer meet the threshold in 2020\nlost_high_bii = (high_2017 & valid_2017) & ~(high_2020 & valid_2020)\n```\n:::\n\n\n## Mapping Lost High-BII Areas\n\nOverlay lost-BII pixels (in red) on the 2020 BII raster.\n\n::: {#c86e7f37 .cell execution_count=9}\n``` {.python .cell-code}\n# ---------------------------------------------------------------\n# Compute true raster aspect ratio (width / height)\n# ---------------------------------------------------------------\n\nbii_aspect_ratio = bii_2020_clip.rio.width / bii_2020_clip.rio.height\n\n# Fix figure height and scale width accordingly\nfig_height = 9\nfig_width = fig_height * bii_aspect_ratio\n\n# Create figure with true array ratio\nfig, ax = plt.subplots(figsize = (fig_width, fig_height))\n\n# ---------------------------------------------------------------\n# Ensure `lost_high_bii` is float mask\n# ---------------------------------------------------------------\n\nlost_high_bii_mask = lost_high_bii.where(lost_high_bii, other = np.nan)\n\n# ---------------------------------------------------------------\n# Plot BII 2020 as the background \n# ---------------------------------------------------------------\n\nbii_plot = bii_2020_clip.plot(ax = ax, cmap = 'Greens',\n                              vmin = 0.1, vmax = 0.88,\n                              add_colorbar = False)\n\n# ---------------------------------------------------------------\n# Overlay lost high-BII areas in red (fixed red color \n# ---------------------------------------------------------------\n\nlost_high_bii_mask.plot(ax = ax, cmap = ListedColormap(['red']), \n                   alpha = 1.0, add_colorbar = False)\n\n# ---------------------------------------------------------------\n# Add Phoenix subdivision outline\n# ---------------------------------------------------------------\n\nphoenix_subdivisions_projection.boundary.plot(ax = ax, color = 'black', linewidth = 1)\n\n# ---------------------------------------------------------------\n#  Add title\n# ---------------------------------------------------------------\n\nax.set_title('Biodiversity Intactness Index (BII)\\nPhoenix Subdivision',\n             fontsize = 16, fontweight = 'bold', pad = 20)\n\nax.axis('off')\n\n# ---------------------------------------------------------------\n# Add colorbar for BII 2020\n# ---------------------------------------------------------------\n\ncbar = plt.colorbar(bii_plot, ax = ax, orientation = 'horizontal', \n                    fraction = 0.046, pad = 0.07)\ncbar.set_label('BII for 2020', fontsize = 12)\n\n# ---------------------------------------------------------------\n# Add red legend entry for lost high-BII pixels\n# ---------------------------------------------------------------\n\nlost_patch = mpatches.Patch(color = 'red', \n                            label = 'Area with BII ≥ 0.75 lost from 2017 to 2020')\n\nax.legend(handles = [lost_patch], \n          loc = 'lower center', \n          bbox_to_anchor = (0.5, -0.075))\n\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](index_files/figure-html/cell-10-output-1.png){width=851 height=795}\n:::\n:::\n\n\n## Interpretation of BII Change (2017 - 2020)\n\nThe map illutrates how biodiversity conditions changed in the Phoenix subdivision between 2017 and 2020. The map shows 2020 BII values in green and highlighted with red in the areas where there has been high biodiversity intactness (BII ≥ 0.75) which no longer meet that threshold. There are larger amount of concentrations of biodiversity loss in the northeastern part of the subdivision while smaller pockets of decline is occuring in the southern and southeastern regions. The urbanization in the area may be correlated reducing local wild habitat and loss of biodiversity.\n\n",
    "supporting": [
      "index_files/figure-html"
    ],
    "filters": [],
    "includes": {}
  }
}